---
- name: Debian - ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Create a folder for Go
  ansible.builtin.file:
    path: "{{ golang_install_dir }}"
    recurse: true

- name: Install Go explicitly
  ansible.builtin.include_role:
    name: gantsign.golang

- name: Install Singularity
  ansible.builtin.include_role:
    name: abims_sbr.singularity
