---
- name: Ensure rsyslog is installed
  ansible.builtin.package:
    name: rsyslog
    state: present

- name: Configure syslog forwarding
  ansible.builtin.template:
    src: "99-forward-syslog.conf"
    dest: "/etc/rsyslog.d/99-forward-syslog.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart rsyslog
