---
- name: Set GPU clocks permissions
  hosts: slurm-node
  become: true
  tasks:
    - name: Install custom facts
      ansible.builtin.include_role:
        name: facts

    - name: Set GPU clocks permissions
      ansible.builtin.command: nvidia-smi -acp UNRESTRICTED
      changed_when: false
      when:
        - ansible_local['gpus']['count'] > 0
  environment: "{{proxy_env if proxy_env is defined else{}}}"
