---
- name: Run NVIDIA GPU tests
  hosts: [kube-node, slurm-node]
  gather_facts: no
  tasks:
    - name: Include NVIDIA GPU tests role
      ansible.builtin.include_role:
        name: nvidia-gpu-tests
