---
- name: Ensure python prereqs are installed
  ansible.builtin.package:
    name:
      - "python3-setuptools"
      - "python3-pip"
    state: present

- name: Ensure docker pip package is installed
  ansible.builtin.pip:
    name: "docker"
    state: present

- name: Log into docker registry
  community.docker.docker_login:
    state: "{{ docker_login_state }}"
    registry: "{{ item.registry }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    reauthorize: "{{ docker_login_reauth }}"
  loop: "{{ docker_login_registries }}"
  no_log: "{{ docker_login_disable_log_password }}"
