---
- name: Ubuntu | remove ppa
  ansible.builtin.apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: Ubuntu | ensure old key is absent
  ansible.builtin.apt_key:
    id: "{{ old_nvidia_driver_ubuntu_cuda_repo_gpgkey_id }}"
    state: "absent"

- name: Ubuntu | install CUDA keyring
  ansible.builtin.apt:
    deb: "{{ nvidia_driver_ubuntu_cuda_keyring_url }}"
    state: "present"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Ubuntu | force apt update
  ansible.builtin.apt:
    update_cache: true
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  changed_when: false

- name: Ubuntu | install default CUDA
  ansible.builtin.package:
    name: "{{ cuda_version }}"
    state: present

- name: Ubuntu | Extra CUDA versions
  when: (cuda_version_extra | length) > 0
  block:
    - name: Ubuntu | Install extra CUDA versions
      ansible.builtin.package:
        name: "{{ cuda_version_extra }}"
        state: present

    - name: Ubuntu | Set default CUDA version
      community.general.alternatives:
        name: cuda
        link: /usr/local/cuda
        path: "/usr/local/cuda-{{ cuda_version_major }}.{{ cuda_version_minor }}"
        state: selected
        priority: "{{ (cuda_version_major ~ cuda_version_minor) | int }}"

- name: Ubuntu | Set default CUDA version
  community.general.alternatives:
    name: cuda
    link: /usr/local/cuda
    path: "/usr/local/cuda-{{ cuda_version_major }}.{{ cuda_version_minor }}"
    priority: "{{ (cuda_version_major ~ cuda_version_minor) | int }}"
    state: auto
  when: (cuda_version_extra | length) == 0
