---
# ##########################################
# Install dependencies
# ##########################################

- name: Set up slurm role
  ansible.builtin.include_tasks:
    file: setup-role.yml

- name: Configure ld.so library path
  ansible.builtin.template:
    src: etc/ld.so.conf.d/slurm.conf.j2
    dest: /etc/ld.so.conf.d/slurm.conf
    mode: "0644"
  notify:
    - Update ld.so cache

- name: Setup munge
  ansible.builtin.include_tasks:
    file: munge.yml

- name: Setup hwloc
  ansible.builtin.include_tasks:
    file: hwloc.yml
  tags: hwloc
  when: slurm_include_hwloc

- name: Setup pmix
  ansible.builtin.include_tasks:
    file: pmix.yml
  tags: pmix
  when: slurm_include_pmix

###########################################
# Build Slurm
###########################################
- name: Setup build variables
  ansible.builtin.set_fact:
    slurm_build: false
    slurm_upgrade: false
    slurm_downgrade: false

- name: Check installed slurm version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      {{ [slurm_install_prefix, 'sbin', 'slurmd'] | path_join | quote }} --version | awk '{print $2}' || echo "0.0.0"
    executable: /bin/bash
  register: slurmd_reported_version
  check_mode: false # never alters the system
  changed_when: false
  failed_when: slurmd_reported_version.rc != 0

- name: Only build slurm on version change, or if forced
  ansible.builtin.set_fact:
    slurm_build: true
  when: slurm_force_rebuild or slurmd_reported_version.stdout != slurm_version

- name: Check if upgrading/downgrading
  ansible.builtin.set_fact:
    slurm_upgrade: "{{ slurmd_reported_version.stdout is version(slurm_version, '<') }}"
    slurm_downgrade: "{{ slurmd_reported_version.stdout is version(slurm_version, '>') }}"
  when: slurm_build

- name: Going to rebuild slurm?
  ansible.builtin.debug:
    msg: "Will build slurm: {{ slurm_build }}"
    verbosity: 0

- name: Install build dependencies
  ansible.builtin.package:
    name: "{{ slurm_build_deps }}"
    state: present

- name: Install build dependencies for sview (if enabled)
  ansible.builtin.package:
    name: "{{ slurm_sview_build_deps }}"
    state: present
  when: slurm_enable_sview

- name: Install build dependencies for NVML (if enabled)
  ansible.builtin.package:
    name: "{{ cuda_version | replace('toolkit', 'nvml-dev') }}"
    state: present
  when: slurm_autodetect_nvml or slurm_enable_nvml

- name: Remove distribution slurm packages (Ubuntu)
  ansible.builtin.apt:
    name:
      - slurm
      - slurm-wlm
      - slurmctld
      - slurmdbd
      - slurmd
      - slurmrestd
      - sview
    state: absent
  when: ansible_distribution == 'Ubuntu'
  failed_when: false

- name: Remove distribution slurm packages (RHEL)
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - slurm
  when: ansible_os_family == 'RedHat'
  failed_when: false

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Check for existing build, uninstall if necessary, and clean up
  when: slurm_build
  block:
    # This service should be stopped before uninstalling slurm
    - name: Stop docker slurm exporter service to prevent subfolder creation
      ansible.builtin.service:
        name: "docker.slurm-exporter.service"
        state: stopped
      when:
        - ansible_distribution == 'Ubuntu'
        - ("docker.slurm-exporter.service" in ansible_facts.services)
      register: slurm_exporter_service_stopped
      failed_when: false # if this fails that's fine, maybe the service doesn't exist or is already stopped

    - name: Check if we have an old build dir
      ansible.builtin.stat:
        path: "{{ slurm_build_dir }}"
      register: slurm_old_build_dir

    - name: Attempt to uninstall old version
      community.general.make:
        target: uninstall
        chdir: "{{ slurm_build_dir }}"
        jobs: "{{ slurm_build_njobs }}"
      failed_when: false # if this fails that's fine, we're purging it next anyway
      when: slurm_old_build_dir.stat.exists

    - name: Remove old build dir
      ansible.builtin.file:
        path: "{{ slurm_build_dir }}"
        state: absent
      when: slurm_old_build_dir.stat.exists

    - name: Remove old lib dir
      ansible.builtin.file:
        path: "{{ slurm_install_prefix }}/lib/slurm"
        state: absent

- name: Build Slurm
  when: slurm_build
  block:
    - name: Create build directory
      ansible.builtin.file:
        path: "{{ slurm_build_dir }}"
        state: directory
        mode: "0755"
      when: slurm_build

    - name: Download slurm source to shared storage
      ansible.builtin.get_url:
        url: "{{ slurm_src_url }}"
        dest: "{{ slurm_src_path }}"
        mode: "0644"
      environment: "{{ proxy_env if proxy_env is defined else {} }}"
      delegate_to: "{{ groups['slurm-node'].0 }}"
      run_once: true # noqa: run-once[task] (any node can do this)

    - name: Extract slurm sources
      ansible.builtin.unarchive:
        src: "{{ slurm_src_path }}"
        dest: "{{ slurm_build_dir }}"
        remote_src: true
        extra_opts:
          - --strip-components=1
        creates: "{{ slurm_build_dir }}/configure"

    - name: Clean slurm src dir
      community.general.make:
        chdir: "{{ slurm_build_dir }}"
        target: distclean
        jobs: "{{ slurm_build_njobs }}"
      failed_when: false # if this fails that's fine

    - name: Configure slurm (without NVML)
      ansible.builtin.command:
        cmd: "{{ slurm_configure }}"
        chdir: "{{ slurm_build_dir }}"
        creates: "{{ slurm_build_dir }}/Makefile"
      when:
        - slurm_build
        - not slurm_autodetect_nvml

    - name: Configure slurm (with NVML)
      ansible.builtin.command:
        cmd: "./configure {{ slurm_configure_nvml }}"
        chdir: "{{ slurm_build_dir }}"
        creates: "{{ slurm_build_dir }}/Makefile"
      when:
        - slurm_build
        - slurm_autodetect_nvml

    - name: Build Slurm
      community.general.make:
        target:
          - all
          - contrib
        chdir: "{{ slurm_build_dir }}"
        jobs: "{{ slurm_build_njobs }}"
      when: slurm_build

    - name: Install Slurm
      community.general.make:
        target:
          - install
          - install-contrib
        chdir: "{{ slurm_build_dir }}"
        jobs: "{{ slurm_build_njobs }}"
      when: slurm_build
      notify:
        - Restart slurmd
        - Restart slurmdbd
        - Restart slurmctld

    - name: Build pam_slurm_adopt
      community.general.make:
        target: all
        chdir: "{{ slurm_build_dir }}/contribs/pam_slurm_adopt"
        jobs: "{{ slurm_build_njobs }}"

    - name: Install pam_slurm_adopt
      community.general.make:
        target: install
        chdir: "{{ slurm_build_dir }}/contribs/pam_slurm_adopt"
        jobs: "{{ slurm_build_njobs }}"
      notify:
        - Restart slurmd
        - Restart slurmdbd
        - Restart slurmctld

- name: Install bash completion script
  ansible.builtin.copy:
    src: "{{ slurm_build_dir }}/contribs/slurm_completion_help/slurm_completion.sh"
    dest: /etc/bash_completion.d/slurm-completion.sh
    mode: "0644"
    owner: root
    group: root
  when: ansible_distribution == 'Ubuntu'

- name: Fix library dir permissions
  ansible.builtin.file:
    path: "{{ slurm_install_prefix }}/lib/slurm"
    state: directory
    mode: "0775"

- name: Fix deepops dir permissions
  ansible.builtin.file:
    path: "{{ deepops_dir }}"
    state: directory
    mode: "0755"

- name: Start docker slurm exporter service again
  ansible.builtin.service:
    name: "docker.slurm-exporter.service"
    state: started
  when:
    - ansible_distribution == 'Ubuntu'
    - ("docker.slurm-exporter.service" in ansible_facts.services)
