---
# ##########################################
# Install dependencies
# ##########################################

- name: Set up slurm role
  ansible.builtin.include_tasks:
    file: setup-role.yml

- name: Configure ld.so library path
  ansible.builtin.template:
    src: etc/ld.so.conf.d/slurm.conf.j2
    dest: /etc/ld.so.conf.d/slurm.conf
    mode: "0644"
  notify:
    - update ld.so cache

- name: Setup munge
  ansible.builtin.include_tasks:
    file: munge.yml

- name: Setup hwlock
  ansible.builtin.include_tasks:
    file: hwloc.yml
  tags: hwloc
  when: slurm_include_hwloc

- name: Setup pmix
  ansible.builtin.include_tasks:
    file: pmix.yml
  tags: pmix
  when: slurm_include_pmix

###########################################
# Build Slurm
###########################################
- name: Setup build variables
  ansible.builtin.set_fact:
    slurm_build: false
    slurm_upgrade: false
    slurm_downgrade: false

- name: Check installed slurm version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      {{ [slurm_install_prefix, 'sbin', 'slurmd'] | path_join | quote }} --version | awk '{print $2}' || echo "0.0.0"
    executable: /bin/bash
  register: slurmd_reported_version
  check_mode: false # never alters the system
  changed_when: false
  failed_when: slurmd_reported_version.rc != 0

- name: Only build slurm on version change, or if forced
  ansible.builtin.set_fact:
    slurm_build: true
  when: slurm_force_rebuild or slurmd_reported_version.stdout != slurm_version

- name: Check if upgrading/downgrading
  ansible.builtin.set_fact:
    slurm_upgrade: "{{ slurmd_reported_version.stdout is version(slurm_version, '<') }}"
    slurm_downgrade: "{{ slurmd_reported_version.stdout is version(slurm_version, '>') }}"
  when: slurm_build

- name: Going to rebuild slurm?
  ansible.builtin.debug:
    msg: "Rebuild Slurm? {{ slurm_build }}"

- name: Install build dependencies
  ansible.builtin.apt:
    name: "{{ slurm_build_deps }}"
    state: present

- name: Install build dependencies
  ansible.builtin.apt:
    name: "{{ cuda_version | replace('toolkit', 'nvml-dev') }}"
    state: present
  when: slurm_autodetect_nvml or slurm_enable_nvml

- name: Remove slurm packages
  ansible.builtin.apt:
    name:
      - slurm
      - slurm-wlm
      - slurmctld
      - slurmdbd
      - slurmd
      - slurmrestd
    state: absent
  when: ansible_distribution == 'Ubuntu'
  failed_when: false

- name: Remove slurm packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - slurm
  when: ansible_os_family == 'RedHat'
  failed_when: false

- name: Gather service facts
  ansible.builtin.service_facts:

- name: When building, try to uninstall first before downloading source
  when: slurm_build
  block:
    # This service should be stopped before uninstalling slurm
    - name: Stop docker slurm exporter service to prevent subfolder creation
      ansible.builtin.service:
        name: "docker.slurm-exporter.service"
        state: stopped
      when: (ansible_distribution == 'Ubuntu') and ("docker.slurm-exporter.service" in ansible_facts.services)

    - name: Check that we have an old build dir
      ansible.builtin.stat:
        path: "{{ slurm_build_dir }}"
      register: slurm_old_build_dir

    - name: Uninstall old verson
      ansible.builtin.command: make -j uninstall
      args:
        chdir: "{{ slurm_build_dir }}"
      failed_when: false
      when: slurm_old_build_dir.stat.exists

    - name: Remove old build dir
      ansible.builtin.file:
        path: "{{ slurm_build_dir }}"
        state: absent

    - name: Remove old lib dir
      ansible.builtin.file:
        path: "{{ slurm_install_prefix }}/lib/slurm"
        state: absent

- name: Make build directory
  ansible.builtin.file:
    path: "{{ slurm_build_dir }}"
    state: directory
    mode: "0755"
  when: slurm_build

- name: Download source
  ansible.builtin.unarchive:
    src: "{{ slurm_src_url }}"
    remote_src: true
    dest: "{{ slurm_build_dir }}"
    extra_opts:
      - --strip-components=1
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when: slurm_build

- name: Clean src dir
  ansible.builtin.command: make distclean
  args:
    chdir: "{{ slurm_build_dir }}"
  failed_when: false
  when: slurm_build

- name: Configure
  ansible.builtin.command: "{{ slurm_configure }}"
  args:
    chdir: "{{ slurm_build_dir }}"
  when: slurm_build and (not slurm_autodetect_nvml)

- name: Configure
  ansible.builtin.command: "{{ slurm_configure_nvml }}"
  args:
    chdir: "{{ slurm_build_dir }}"
  when: slurm_build and slurm_autodetect_nvml

- name: Build
  ansible.builtin.shell: "make -j$(nproc) > build.log 2>&1"
  args:
    chdir: "{{ slurm_build_dir }}"
  when: slurm_build

- name: Build contrib
  ansible.builtin.shell: "make -j$(nproc) contrib >> build.log 2>&1"
  args:
    chdir: "{{ slurm_build_dir }}"
  when: slurm_build

- name: Install
  ansible.builtin.shell: "make -j$(nproc) install >> build.log 2>&1"
  args:
    chdir: "{{ slurm_build_dir }}"
  when: slurm_build
  notify:
    - Restart slurmd
    - Restart slurmdbd
    - Restart slurmctld

- name: Install contrib
  ansible.builtin.shell: "make -j$(nproc) install-contrib >> build.log 2>&1"
  args:
    chdir: "{{ slurm_build_dir }}"
  when: slurm_build
  notify:
    - Restart slurmd
    - Restart slurmdbd
    - Restart slurmctld

- name: Build pam_slurm_adopt
  ansible.builtin.shell: "make -j$(nproc) >> ../../build.log 2>&1"
  args:
    chdir: "{{ slurm_build_dir }}/contribs/pam_slurm_adopt"
  when: slurm_build

- name: Install pam_slurm_adopt
  ansible.builtin.shell: "make -j$(nproc) install >> ../../build.log 2>&1"
  args:
    chdir: "{{ slurm_build_dir }}/contribs/pam_slurm_adopt"
  when: slurm_build
  notify:
    - Restart slurmd
    - Restart slurmdbd
    - Restart slurmctld

- name: Fix library dir permissions
  ansible.builtin.file:
    path: "{{ slurm_install_prefix }}/lib/slurm"
    state: directory
    mode: "0775"

- name: Fix deepops dir permissions
  ansible.builtin.file:
    path: "{{ deepops_dir }}"
    state: directory
    mode: "0755"
    recurse: true

- name: Start docker slurm exporter service again
  ansible.builtin.service:
    name: "docker.slurm-exporter.service"
    state: restarted
  when: (ansible_distribution == 'Ubuntu') and ("docker.slurm-exporter.service" in ansible_facts.services)
