---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - numactl
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install dependencies
  ansible.builtin.package:
    name:
      - numactl
      - psmisc
    state: present
  when: ansible_os_family == "RedHat"

- name: Add cgroups to grub options
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    insertafter: "^GRUB_CMDLINE_LINUX=[^\\\\$]"
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} cgroup_enable=memory swapaccount=1"'
  register: update_grub

- name: Update grub
  when: update_grub.changed and ansible_os_family == "Debian"
  block:
    - name: Update grub
      ansible.builtin.command: update-grub
      register: update_grub_cmd
      changed_when: update_grub_cmd.rc == 0
    # - name: reboot after updating grub config
    #   reboot:
    #     reboot_timeout: "{{ slurm_node_reboot_timeout }}"

- name: Update grub
  when: update_grub.changed and ansible_os_family == "RedHat"
  block:
    - name: Update grub
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
      register: grub2_mkconfig_cmd
      changed_when: grub2_mkconfig_cmd.rc == 0
    # - name: Reboot after updating grub config
    #   ansible.builtin.reboot:
    #     reboot_timeout: "{{ slurm_node_reboot_timeout }}"

- name: Create sysconfig dir
  ansible.builtin.file:
    path: "{{ slurm_sysconf_dir }}"
    state: directory
    owner: root
    mode: "0755"

- name: Create slurm directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: "0755"
  with_items:
    - "{{ slurm_config_dir }}"
    - "{{ slurm_config_dir }}/shared"
    - "{{ slurm_config_dir }}/shared/bin"
    - /var/log/slurm
    - /var/spool/slurm/d
  tags:
    - prolog
    - epilog

- name: Configure slurmd for pmix
  ansible.builtin.blockinfile:
    path: "{{ slurm_sysconf_dir }}/slurmd"
    create: true
    mode: "0644"
    block: |
      PMIX_MCA_ptl=^usock
      PMIX_MCA_psec=none
      PMIX_SYSTEM_TMPDIR=/var/empty
      PMIX_MCA_gds=hash
  notify: Restart slurmd
  tags: config

- name: Copy shared scripts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ slurm_config_dir }}/shared/bin/"
    mode: "0755"
  with_fileglob:
    - templates/etc/slurm/shared/bin/*
  tags:
    - prolog
    - epilog

- name: Include prolog/epilog
  ansible.builtin.include_tasks: prolog_epilog.yml
  when: slurm_enable_prolog_epilog

- name: Create slurm.conf (per-host mode)
  ansible.builtin.template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    mode: "0644"
  when: not slurm_conf_symlink
  notify:
    - Restart slurmctld
  tags:
    - config

- name: Symlink slurm.conf (shared mode)
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/slurm.conf"
    state: link
    src: "{{ slurmctl_config_dir }}/slurm.conf"
    force: true
  when: slurm_conf_symlink
  notify:
    - Restart slurmctld
  tags:
    - config

- name: Configure cgroup.conf
  ansible.builtin.template:
    src: "{{ slurm_cgroup_conf_template }}"
    dest: "{{ slurm_config_dir }}/cgroup.conf"
    mode: "0644"
  notify:
    - Restart slurmd
  tags:
    - config

- name: Configure gres.conf
  ansible.builtin.template:
    src: "{{ slurm_gres_conf_template }}"
    dest: "{{ slurm_config_dir }}/gres.conf"
    mode: "0644"
  notify:
    - Restart slurmd
  tags:
    - config

- name: Start slurmd
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    enabled: true
    daemon-reload: true

- name: Install /etc/localusers
  ansible.builtin.template:
    src: etc/localusers
    dest: "{{ item }}"
    mode: "0600"
  with_items:
    - "{{ slurm_config_dir }}/localusers.backup"
    - /etc/localusers
  tags:
    - localusers

- name: Configure /etc/pam.d/sshd to restrict node access without jobs
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sshd
    block: |
      -account sufficient {{ slurm_pam_lib_dir }}/pam_slurm_adopt.so action_no_jobs=ignore
      -account sufficient pam_listfile.so item=user sense=allow file=/etc/localusers
      -account required {{ slurm_pam_lib_dir }}/pam_slurm_adopt.so
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ansible-role-slurm)"
  tags:
    - config
  when:
    - slurm_enable_pam_slurm_adopt
    - slurm_restrict_node_access

- name: Configure /etc/pam.d/sshd to adopt processes but not otherwise deny access
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sshd
    block: |
      -account sufficient {{ slurm_pam_lib_dir }}/pam_slurm_adopt.so action_no_jobs=ignore
      -account sufficient pam_listfile.so item=user sense=allow file=/etc/localusers
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ansible-role-slurm)"
  tags:
    - config
  when:
    - slurm_enable_pam_slurm_adopt
    - not slurm_restrict_node_access

- name: Comment out pam_systemd.so as it conflicts with pam_slurm_adapt.so, see https://slurm.schedmd.com/pam_slurm_adopt.html
  ansible.builtin.replace:
    path: /etc/pam.d/common-session
    regexp: "^([^#].*pam_systemd.so.*)"
    replace: "# \\1 # ANSIBLE MANAGED (ansible-role-slurm)"
  when:
    - ansible_distribution == 'Ubuntu'
    - slurm_enable_pam_slurm_adopt
  tags:
    - config

- name: Comment out pam_systemd.so in RHEL as it conflicts with pam_slurm_adapt.so, see https://slurm.schedmd.com/pam_slurm_adopt.html
  ansible.builtin.replace:
    path: /etc/pam.d/password-auth
    regexp: "^([^#].*pam_systemd.so.*)"
    replace: "# \\1 # ANSIBLE MANAGED (ansible-role-slurm)"
  when:
    - ansible_os_family == "RedHat"
    - slurm_enable_pam_slurm_adopt
  tags:
    - config
