---
- name: install dependencies
  apt:
    name:
      - mariadb-server
      - python3-mysqldb
      - s-nail
      - ssmtp
    state: present
    cache_valid_time: 3600

- name: setup slurm db user
  mysql_user:
    name: "{{ slurm_db_username }}"
    password: "{{ slurm_db_password }}"
    priv: "*.*:USAGE/slurm_acct_db.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: 0755
  with_items:
    - "{{ slurm_config_dir }}"
    - "{{ slurmctl_config_dir }}"
    - /var/spool/slurm/ctld
    - /var/log/slurm

- name: create slurm HA directory
  file:
    path: "{{ slurm_ha_state_save_location }}"
    state: directory
    owner: slurm
    mode: 0755
  when: slurm_enable_ha

- name: Create slurm.conf (per-host mode)
  template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    mode: "0644"
  when: not slurm_conf_symlink
  notify:
    - restart slurmctld
  tags:
    - config

- name: Create slurm.conf (shared mode)
  template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurmctl_config_dir }}/slurm.conf"
    mode: "0644"
  when: slurm_conf_symlink
  tags:
    - config

- name: Symlink slurm.conf (shared mode)
  file:
    path: "{{ slurm_config_dir }}/slurm.conf"
    state: link
    src: "{{ slurmctl_config_dir }}/slurm.conf"
    force: yes
  when: slurm_conf_symlink
  notify:
    - restart slurmctld
  tags:
    - config

- name: Configure slurmdbd
  template:
    src: "{{ slurm_dbd_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurmdbd.conf"
    owner: "{{ slurm_username }}"
    mode: 0600
  notify:
    - restart slurmdbd
  tags:
    - config

- name: restart slurmdbd
  systemd:
    name: slurmdbd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: wait for slurmdbd to be available
  wait_for:
    port: 6819
    delay: 5

- name: create cluster
  command: sacctmgr -i add cluster {{ slurm_cluster_name }}
  register: create_cluster_result
  failed_when: "create_cluster_result.rc != 0 and 'already exists' not in create_cluster_result.stdout"
  changed_when: "'already exists' not in create_cluster_result.stdout"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"
  run_once: true

- name: create account
  command: sacctmgr -i add account compute-account Description="Compute Accounts" Organization="Prestige"
  register: create_account_result
  failed_when: "create_account_result.rc != 0 and 'Nothing added' not in create_account_result.stdout and 'Already existing account' not in create_account_result.stdout"
  changed_when: "'Nothing added' not in create_account_result.stdout and 'Already existing account' not in create_account_result.stdout"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: create users
  command: sacctmgr -i create user {{ item }} account=compute-account adminlevel=None
  register: create_user_result
  failed_when: "create_user_result.rc != 0 and 'Nothing added' not in create_user_result.stdout and 'Already existing account' not in create_user_result.stdout"
  changed_when: "'Nothing added' not in create_user_result.stdout and 'Already existing account' not in create_user_result.stdout"
  with_items:
    - "{{ user }}"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: clear slurm state when downgrading
  command: slurmctld -i
  when: slurm_downgrade
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: wait for slurmctld to start
  pause:
    seconds: 20
  when: slurm_downgrade

- name: kill slurmctld
  command: killall slurmctld
  failed_when: false
  when: slurm_downgrade

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted
    enabled: yes
    daemon-reload: yes
