---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - mariadb-server
      - python3-mysqldb
      - s-nail
      - ssmtp
    state: present

- name: Setup slurm db user
  community.mysql.mysql_user:
    name: "{{ slurm_db_username }}"
    password: "{{ slurm_db_password }}"
    priv: "*.*:USAGE/slurm_acct_db.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create slurm directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: "0755"
  loop:
    - "{{ slurm_config_dir }}"
    - "{{ slurmctl_config_dir }}"
    - /var/spool/slurm/ctld
    - /var/log/slurm

- name: Create slurm HA directory
  ansible.builtin.file:
    path: "{{ slurm_ha_state_save_location }}"
    state: directory
    owner: slurm
    mode: "0755"
  when: slurm_enable_ha

- name: Create slurm.conf (per-host mode)
  ansible.builtin.template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    mode: "0644"
  when: not slurm_conf_symlink
  notify:
    - Restart slurmctld
    - Restart slurmrestd
  tags:
    - config

- name: Create slurm.conf (shared mode)
  ansible.builtin.template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurmctl_config_dir }}/slurm.conf"
    mode: "0644"
  when: slurm_conf_symlink and is_first_controller
  tags:
    - config

- name: Symlink slurm.conf on all nodes (shared mode)
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/slurm.conf"
    state: link
    src: "{{ slurmctl_config_dir }}/slurm.conf"
    force: true
  when: slurm_conf_symlink
  notify:
    - Restart slurmctld
    - Restart slurmrestd
  tags:
    - config

- name: Set up slurmrestd
  when: slurm_include_slurmrestd
  block:
    - name: Create JWT key for slurmrestd
      ansible.builtin.command:
        cmd: dd if=/dev/random of={{ inventory_dir }}/secrets/slurmrestd_jwt_hs256.key bs=32 count=1
        creates: "{{ inventory_dir }}/secrets/slurmrestd_jwt_hs256.key"
      changed_when: false # doesn't actually change target hosts at all
      delegate_to: localhost
      run_once: true

    - name: Copy JWT key to controllers
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/secrets/slurmrestd_jwt_hs256.key"
        dest: "{{ slurm_restd_jwt_key_path }}"
        owner: "{{ slurm_username }}"
        mode: "0600"
        group: "{{ slurm_user_gid | default(slurm_username) }}"

    - name: Set ACL on JWT key to allow slurmrestd user to read it
      ansible.posix.acl:
        path: "{{ slurm_restd_jwt_key_path }}"
        entity: "{{ slurm_restd_username }}"
        etype: user
        permissions: r
        state: present
      when: slurm_restd_username != slurm_username

- name: Configure slurmdbd
  ansible.builtin.template:
    src: "{{ slurm_dbd_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurmdbd.conf"
    owner: "{{ slurm_username }}"
    mode: "0600"
  notify:
    - Restart slurmdbd
  tags:
    - config

- name: Restart slurmdbd # noqa no-handler (needs to happen *now*)
  ansible.builtin.systemd:
    name: slurmdbd
    state: restarted
    enabled: true
    daemon-reload: true
  when: slurmdbd_conf_result.changed

- name: Wait for slurmdbd to be available
  ansible.builtin.wait_for:
    port: 6819
    delay: 5

- name: Create cluster
  ansible.builtin.command:
    cmd: sacctmgr -i add cluster {{ slurm_cluster_name }}
  register: create_cluster_result
  failed_when: "create_cluster_result.rc != 0 and 'already exists' not in create_cluster_result.stdout"
  changed_when: "'already exists' not in create_cluster_result.stdout"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"
  run_once: true

- name: Create account
  ansible.builtin.command:
    cmd: sacctmgr -i add account compute-account Description="Compute Accounts" Organization="Prestige"
  register: create_account_result
  failed_when:
    - create_account_result.rc != 0
    - \"Nothing added" not in create_account_result.stdout
    - \"Already existing account" not in create_account_result.stdout
  changed_when:
    - \"Nothing added" not in create_account_result.stdout
    - \"Already existing account" not in create_account_result.stdout
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: Create users
  ansible.builtin.command:
    cmd: sacctmgr -i create user {{ item }} account=compute-account adminlevel=None
  register: create_user_result
  failed_when:
    - create_user_result.rc != 0
    - \"Nothing added" not in create_user_result.stdout
    - \"Already existing account" not in create_user_result.stdout
  changed_when:
    - \"Nothing added" not in create_user_result.stdout
    - \"Already existing account" not in create_user_result.stdout
  loop:
    - "{{ user }}"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: Clear slurm state when downgrading
  ansible.builtin.command: slurmctld -i
  when: slurm_downgrade
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: Wait for slurmctld to start
  ansible.builtin.pause:
    seconds: 20
  when: slurm_downgrade

- name: Kill slurmrestd
  ansible.builtin.command:
    cmd: killall slurmrestd
  changed_when: false
  failed_when: false
  when: slurm_include_slurmrestd and slurm_downgrade

- name: Kill slurmctld
  ansible.builtin.command:
    cmd: killall slurmctld
  changed_when: false
  failed_when: false
  when: slurm_downgrade

- name: Restart slurmctld
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    enabled: true
    daemon-reload: true

- name: Restart slurmrestd
  ansible.builtin.systemd:
    name: slurmrestd
    state: restarted
    enabled: true
    daemon-reload: true
  when: slurm_include_slurmrestd
