---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-mysqldb
      - s-nail
      - ssmtp
    state: present
    cache_valid_time: 3600

- name: Setup slurm db user
  community.mysql.mysql_user:
    name: "{{ slurm_db_username }}"
    password: "{{ slurm_db_password }}"
    priv: "*.*:USAGE/slurm_acct_db.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create slurm directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: "0755"
  with_items:
    - "{{ slurm_config_dir }}"
    - "{{ slurmctl_config_dir }}"
    - /var/spool/slurm/ctld
    - /var/log/slurm

- name: Create slurm HA directory
  ansible.builtin.file:
    path: "{{ slurm_ha_state_save_location }}"
    state: directory
    owner: slurm
    mode: "0755"
  when: slurm_enable_ha

- name: Create slurm.conf (per-host mode)
  ansible.builtin.template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    mode: "0644"
  when: not slurm_conf_symlink
  notify:
    - Restart slurmctld
  tags:
    - config

- name: Create slurm.conf (shared mode)
  ansible.builtin.template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurmctl_config_dir }}/slurm.conf"
    mode: "0644"
  when: slurm_conf_symlink and is_first_controller
  tags:
    - config

- name: Symlink slurm.conf (shared mode)
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/slurm.conf"
    state: link
    src: "{{ slurmctl_config_dir }}/slurm.conf"
    force: true
  when: slurm_conf_symlink
  notify:
    - Restart slurmctld
  tags:
    - config

- name: Configure slurmdbd
  ansible.builtin.template:
    src: "{{ slurm_dbd_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurmdbd.conf"
    owner: "{{ slurm_username }}"
    mode: "0600"
  notify:
    - Restart slurmdbd
  tags:
    - config

- name: Restart slurmdbd
  ansible.builtin.systemd:
    name: slurmdbd
    state: restarted
    enabled: true
    daemon-reload: true

- name: Wait for slurmdbd to be available
  ansible.builtin.wait_for:
    port: 6819
    delay: 5

- name: Create cluster
  ansible.builtin.command:
    cmd: sacctmgr -i add cluster {{ slurm_cluster_name }}
  register: create_cluster_result
  failed_when: "create_cluster_result.rc != 0 and 'already exists' not in create_cluster_result.stdout"
  changed_when: "'already exists' not in create_cluster_result.stdout"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"
  run_once: true

- name: Create account
  ansible.builtin.command:
    cmd: sacctmgr -i add account compute-account Description="Compute Accounts" Organization="Prestige"
  register: create_account_result
  failed_when: "create_account_result.rc != 0 and 'Nothing added' not in create_account_result.stdout and 'Already existing account' not in create_account_result.stdout"
  changed_when: "'Nothing added' not in create_account_result.stdout and 'Already existing account' not in create_account_result.stdout"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: Create users
  ansible.builtin.command:
    cmd: sacctmgr -i create user {{ item }} account=compute-account adminlevel=None
  register: create_user_result
  failed_when: "create_user_result.rc != 0 and 'Nothing added' not in create_user_result.stdout and 'Already existing account' not in create_user_result.stdout"
  changed_when: "'Nothing added' not in create_user_result.stdout and 'Already existing account' not in create_user_result.stdout"
  with_items:
    - "{{ user }}"
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: Clear slurm state when downgrading
  ansible.builtin.command: slurmctld -i
  when: slurm_downgrade
  environment:
    PATH: "{{ slurm_install_prefix }}/bin:{{ ansible_env.PATH }}"

- name: Wait for slurmctld to start
  ansible.builtin.pause:
    seconds: 20
  when: slurm_downgrade

- name: Kill slurmctld
  ansible.builtin.command:
    cmd: killall slurmctld
  changed_when: false
  failed_when: false
  when: slurm_downgrade

- name: Restart slurmctld
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    enabled: true
    daemon-reload: true
