---
- name: Default to building hwloc
  ansible.builtin.set_fact:
    slurm_hwloc_build: true

- name: Check installed hwloc version
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      {{ hwloc_install_prefix }}/bin/hwloc-info --version | sed -E 's/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/'
    executable: /bin/bash
  register: hwloc_info_version
  failed_when: false
  changed_when: hwloc_info_version.rc != 0

- name: Don't build hwloc if it's already installed, unless forced
  ansible.builtin.set_fact:
    slurm_hwloc_build: false
  when:
    - hwloc_version in hwloc_info_version.stdout
    - not hwloc_force_rebuild

- name: Install hwloc build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ slurm_hwloc_deps }}"
  when: ansible_distribution == 'Ubuntu'

- name: Remove hwloc packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - hwloc
    - libhwloc-dev
    - libhwloc5
  when: ansible_distribution == 'Ubuntu'
  failed_when: false

- name: Uninstall old hwloc and clean up
  when: slurm_hwloc_build
  block:
    - name: Check if we have an old build dir
      ansible.builtin.stat:
        path: "{{ hwloc_build_dir }}"
      register: slurm_hwloc_old_build_dir

    - name: Uninstall old hwloc verson
      community.general.make:
        chdir: "{{ hwloc_build_dir }}"
        target: uninstall
        jobs: "{{ slurm_build_njobs }}"
      failed_when: false
      when: slurm_hwloc_old_build_dir.stat.exists

    - name: Remove old hwloc build dir
      ansible.builtin.file:
        path: "{{ hwloc_build_dir }}"
        state: absent
      when: slurm_hwloc_old_build_dir.stat.exists

- name: Build hwloc
  when: slurm_hwloc_build
  block:
    - name: Make hwloc build directory
      ansible.builtin.file:
        path: "{{ hwloc_build_dir }}"
        state: directory
        mode: "0755"

    - name: Download hwloc source to shared storage
      ansible.builtin.get_url:
        url: "{{ hwloc_src_url }}"
        dest: "{{ hwloc_src_path }}"
        mode: "0644"
        checksum: "sha1:{{ hwloc_src_sha1 }}"
      environment: "{{ proxy_env if proxy_env is defined else {} }}"
      delegate_to: "{{ groups['slurm-node'].0 }}"
      run_once: true # noqa: run-once[task] (any node can do this)

    - name: Extract hwloc source
      ansible.builtin.unarchive:
        src: "{{ hwloc_src_path }}"
        dest: "{{ hwloc_build_dir }}"
        remote_src: true
        extra_opts:
          - --strip-components=1
        creates: "{{ hwloc_build_dir }}/configure"

    - name: Clean hwloc src dir
      community.general.make:
        chdir: "{{ hwloc_build_dir }}"
        target: distclean
      failed_when: false

    - name: Configure hwloc
      ansible.builtin.command:
        cmd: "{{ hwloc_configure }}"
        chdir: "{{ hwloc_build_dir }}"
        creates: "{{ hwloc_build_dir }}/Makefile"

    - name: Build hwloc
      community.general.make:
        chdir: "{{ hwloc_build_dir }}"
        target: all
        jobs: "{{ slurm_build_njobs }}"

    - name: Install hwloc
      community.general.make:
        chdir: "{{ hwloc_build_dir }}"
        target: install
        jobs: "{{ slurm_build_njobs }}"
