---
- name: Install CUDA when we require NVML support for autodetection
  ansible.builtin.include_role:
    name: nvidia_cuda
  when: slurm_autodetect_nvml | default(false)

- name: Setup role
  ansible.builtin.include_tasks:
    file: setup-role.yml

- name: Setup build
  ansible.builtin.include_tasks:
    file: build.yml
  tags: build
  when: slurm_workflow_build

- name: Setup slurm systemd services
  ansible.builtin.include_tasks:
    file: service-files.yml

- name: Setup slurm user environment
  ansible.builtin.include_tasks:
    file: setup-user.yml

- name: Setup slurm controller
  ansible.builtin.include_tasks:
    file: controller.yml
  when: is_controller

- name: Setup slurm on compute nodes
  ansible.builtin.include_tasks:
    file: compute.yml
  when: is_compute

- name: Setup slurm on other nodes
  ansible.builtin.include_tasks:
    file: misc-node.yml
  when: is_misc

- name: Apply shm fix
  ansible.builtin.include_tasks:
    file: shmfix.yml
  when: is_compute and slurm_fix_shm

- name: Setup logging
  ansible.builtin.include_tasks:
    file: logging.yml
  tags:
    - rsyslog
    - logging

- name: Setup undrain
  ansible.builtin.include_tasks:
    file: undrain.yml
  when: is_compute

- name: Cleanup
  ansible.builtin.include_tasks:
    file: build-cleanup.yml
