---
- name: Install CUDA when we require NVML support for autodetection
  include_role:
    name: nvidia_cuda
  when: slurm_autodetect_nvml|default(false)

- include_tasks: setup-role.yml

- include_tasks: build.yml
  tags: build
  when: slurm_workflow_build

- include_tasks: service-files.yml

- include_tasks: setup-user.yml

- include_tasks: controller.yml
  when: is_controller

- include_tasks: compute.yml
  when: is_compute

- include_tasks: misc-node.yml
  when: (not is_compute) and (not is_controller)

- include_tasks: shmfix.yml
  when: is_compute and slurm_fix_shm

- include_tasks: logging.yml
  tags:
    - rsyslog
    - logging

- include_tasks: undrain.yml
  when: is_compute

- include_tasks: build-cleanup.yml
