---
# Configure nodes that are neither running controller services, nor slurmd.
# Examples include login nodes or CI nodes.

- name: Create slurm directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: "0755"
  with_items:
    - "{{ slurm_config_dir }}"

- name: Configure slurm.conf
  ansible.builtin.template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    mode: "0644"
  tags:
    - config

- name: Ensure all slurm services are stopped
  ansible.builtin.service:
    name:
      - slurmctld
      - slurmd
      - slurmdbd
    state: stopped
    enabled: false
  failed_when: false # OK for services to not exist yet
