---
- name: Install munge
  ansible.builtin.package:
    name: munge
    state: present
  notify:
    - Restart munge

- name: Create munge.key
  ansible.builtin.template:
    src: templates/etc/munge/munge.key.j2
    dest: /etc/munge/munge.key
    mode: "0400"
    owner: munge
  notify:
    - Restart munge

- name: Start munge
  ansible.builtin.service:
    name: munge
    enabled: true
    state: started

- name: Flush handlers to ensure munge gets restarted now
  ansible.builtin.meta: flush_handlers
