---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - linux-tools-{{ ansible_kernel }} # for cpupower, used in prolog+epilog
  when: ansible_os_family == "Debian"

- name: Install dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
  with_items:
    - kernel-tools # for cpupower, used in prolog+epilog
  when: ansible_os_family == "RedHat"

- name: Delete old prolog files
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/{{ item }}"
    state: absent
  with_items:
    - prolog.sh
    - prolog.d
    - prolog-parts.d
    - prolog-exclusive.d
  tags: prolog
  when: slurm_clear_old_prolog_epilog

- name: Delete old epilog files
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/{{ item }}"
    state: absent
  with_items:
    - epilog.sh
    - epilog.d
    - epilog-parts.d
    - epilog-exclusive.d
    - epilog-last-user.d
  tags: epilog
  when: slurm_clear_old_prolog_epilog

- name: Create prolog directories
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: "0755"
  with_items:
    - prolog.d/
  tags:
    - prolog

- name: Create epilog directories
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: "0755"
  with_items:
    - epilog.d/
  tags:
    - epilog

- name: Copy prolog script
  ansible.builtin.template:
    src: etc/slurm/prolog.sh
    dest: "{{ slurm_config_dir }}/"
    mode: "0755"
  tags:
    - prolog

- name: Copy prolog parts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ slurm_config_dir }}/prolog.d/"
    owner: slurm
    group: slurm
    mode: "0755"
  with_fileglob: "{{ prolog_fileglob }}"
  tags:
    - prolog

- name: Copy epilog script
  ansible.builtin.template:
    src: etc/slurm/epilog.sh
    dest: "{{ slurm_config_dir }}/"
    mode: "0755"
  tags:
    - epilog

- name: Copy epilog parts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ slurm_config_dir }}/epilog.d/"
    owner: slurm
    group: slurm
    mode: "0755"
  with_fileglob: "{{ epilog_fileglob }}"
  tags:
    - epilog
