---
- name: Create slurm user home
  ansible.builtin.file:
    path: "{{ slurm_user_home }}"
    recurse: true
    state: directory

- name: Create slurm user
  ansible.builtin.user:
    name: "{{ slurm_username }}"
    state: present
    system: true
    home: "{{ slurm_user_home }}"
    uid: "{{ slurm_user_uid }}"
