#
# ansible role to install lmod:
#
---
- name: Install packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - bash
      - tcsh
      - lmod
    state: present
  when: ansible_os_family == "Debian"

- name: Create lmod software path directory
  become: true
  ansible.builtin.file:
    path: "{{ sm_software_path }}"
    state: directory
    mode: "0755"

- name: Create lmod module path directory
  become: true
  ansible.builtin.file:
    path: "{{ sm_module_path }}"
    state: directory
    mode: "0755"

- name: Configure lmod bash profile
  become: true
  ansible.builtin.template:
    src: templates/z00_lmod.sh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: "0755"
  tags:
    - configuration

- name: Configure lmod csh profile
  become: true
  ansible.builtin.template:
    src: templates/z00_lmod.csh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: "0755"
  tags:
    - configuration

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891541
- name: Bugfix for lmod posix_c
  become: true
  register: lmod_bugfix_posix
  ansible.builtin.file:
    src: "/usr/lib/x86_64-linux-gnu/lua/{{ item }}/posix_c.so"
    dest: "/usr/lib/x86_64-linux-gnu/lua/{{ item }}/posix.so"
    owner: "root"
    group: "root"
    state: "link"
    force: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
  with_items:
    - "5.1"
    - "5.2"
    - "5.3"

- name: Unset previous lmod setup
  ansible.builtin.shell: unset MODULEPATH_ROOT # noqa command-instead-of-shell
  register: unset_lmod_bash
  args:
    executable: /bin/bash
  changed_when: unset_lmod_bash.rc != 0

- name: Unset previous lmod setup (csh)
  ansible.builtin.shell: unsetenv MODULEPATH_ROOT # noqa command-instead-of-shell
  register: unset_lmod_csh
  args:
    executable: /bin/csh
  changed_when: unset_lmod_csh.rc != 0

- name: Auto load lmod
  ansible.builtin.shell: . /etc/profile.d/z00_lmod.sh # noqa command-instead-of-shell
  register: load_lmod_bash
  args:
    executable: /bin/bash
  changed_when: load_lmod_bash.rc != 0

- name: Auto load lmod (csh)
  ansible.builtin.shell: source /etc/profile.d/z00_lmod.csh # noqa command-instead-of-shell
  register: load_lmod_csh
  args:
    executable: /bin/csh
  changed_when: load_lmod_csh.rc != 0
