---
- name: "Gather os specific variables"
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - ../vars
      skip: true
  tags:
    - always

- name: Default to building NHC
  ansible.builtin.set_fact:
    nhc_build: true

- name: Check if nhc is installed
  ansible.builtin.command:
    cmd: ls -l {{ nhc_install_dir }}/sbin/nhc
  register: nhc_check
  ignore_errors: true
  changed_when: nhc_check.rc != 0

- name: Don't build if installed unless we force
  ansible.builtin.set_fact:
    nhc_build: false
  when: nhc_check.rc == 0 and not nhc_force_reinstall

- name: Install build dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ nhc_build_deps }}"

- name: Ensure build dir exists
  ansible.builtin.file:
    path: "{{ nhc_build_dir }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when: nhc_build

- name: Download nhc src
  ansible.builtin.get_url:
    url: "{{ nhc_src_url }}"
    dest: "{{ nhc_build_dir }}/nhc-{{ nhc_version }}.tar.xz"
    mode: "0644"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when: nhc_build

- name: Extract nhc src
  ansible.builtin.unarchive:
    src: "{{ nhc_build_dir }}/nhc-{{ nhc_version }}.tar.xz"
    dest: "{{ nhc_build_dir }}/"
    remote_src: true
  when: nhc_build

- name: Configure nhc
  ansible.builtin.command:
    cmd: "{{ nhc_configure }}"
    chdir: "{{ nhc_extract_dir }}"
    creates: "{{ nhc_extract_dir }}/Makefile"
  when: nhc_build

- name: Test nhc src
  ansible.builtin.command:
    cmd: "{{ nhc_test }}"
    chdir: "{{ nhc_extract_dir }}"
  changed_when: false
  when: nhc_build and nhc_run_test

- name: Make and install nhc
  ansible.builtin.command:
    cmd: "{{ nhc_make }}"
    chdir: "{{ nhc_extract_dir }}"
    creates: "{{ nhc_install_dir }}/sbin/nhc"
  when: nhc_build

- name: Add deepops checks to nhc
  ansible.builtin.copy:
    src: "deepops.nhc"
    dest: "{{ nhc_config_dir }}/nhc/scripts/deepops.nhc"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Install NHC config
  ansible.builtin.template:
    src: "{{ nhc_config_template }}"
    dest: "{{ nhc_config_dir }}/nhc/nhc.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Create sysconfig dir
  ansible.builtin.file:
    path: "{{ nhc_sysconfig_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add sysconfig to use slurm
  ansible.builtin.template:
    src: "{{ nhc_sysconfig_template }}"
    dest: "{{ nhc_sysconfig_dir }}/nhc"
    owner: root
    group: root
    mode: "0644"
