---
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - ../vars
      skip: true
  tags: vars

- name: Setup Open OnDemand server
  ansible.builtin.include_tasks: server.yml
  when: ood_is_server

- name: Setup Open OnDemand client
  ansible.builtin.include_tasks: client.yml
  when: ood_is_client

- name: Setup linuxhost adapter
  ansible.builtin.include_tasks: linuxhost-adapter.yml
  when: ood_is_server and ood_install_linuxhost_adapter
