---
- name: Restart munge
  ansible.builtin.service:
    name: munge
    state: restarted

- name: Restart slurmd
  ansible.builtin.service:
    name: slurmd
    state: restarted
  when: is_compute

- name: Restart slurmdbd
  ansible.builtin.service:
    name: slurmdbd
    state: restarted
  when: is_controller

- name: Restart slurmctld
  ansible.builtin.service:
    name: slurmctld
    state: restarted
  when: is_controller

- name: Restart logind
  ansible.builtin.service:
    name: systemd-logind.service
    state: restarted
    enabled: true
  when: is_compute
