---
- name: install ubuntu packages
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - nfs

- name: ensure export path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    mode: "0755"
  with_items: "{{ nfs_exports }}"
  notify: Restart nfs
  tags:
    - nfs

- name: ensure statd is enabled
  ansible.builtin.service:
    name: rpc-statd
    enabled: true
    state: started
  notify:
    - Restart rpcbind
    - Restart nfs
  tags:
    - nfs

- name: configure exports
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Restart nfs
  register: nfs_exports_copy
  tags:
    - nfs

- name: ensure nfs server is running
  ansible.builtin.service:
    name: "{{ nfs_server_daemon }}"
    state: started
    enabled: true
  when: nfs_exports|length
  tags:
    - nfs
