{
 "title": "Slurm Dashboard",
 "description": "Slurm exporter statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(slurm_partition_total_cpus, partition)"
    }
   },
   {
    "name": "jobid",
    "query": {
     "query": "label_values(slurm_proc_cpu_usage, jobid)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(slurm_partition_total_cpus,instance)"
    }
   },
   {
    "name": "state",
    "label": "Job State",
    "query": {
     "query": "label_values(slurm_partition_job_state_total,state)"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(slurm_user_cpus_pending,user)"
    }
   },
   {
    "name": "account",
    "label": "Account",
    "query": {
     "query": "label_values(slurm_account_cpus_pending,account)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Partition ($partition) Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Partition ($partition) Alloc vs Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(partition) (slurm_partition_alloc_cpus{partition=~\"$partition\", state=\"allocated\"}) / sum by(partition) (slurm_partition_total_cpus{partition=~\"$partition\"})",
     "legendFormat": "{{partition}} cpuA"
    },
    {
     "expr": "sum by(partition) (slurm_partition_alloc_mem{partition=~\"$partition\", state=\"allocated\"}) / sum by(partition) (slurm_partition_real_mem{partition=~\"$partition\"})",
     "legendFormat": "{{partition}} memA"
    },
    {
     "expr": "slurm_partition_cpu_load{partition=~\"$partition\"} / slurm_partition_total_cpus{partition=~\"$partition\"}",
     "legendFormat": "{{partition}} cpuL"
    }
   ]
  },
  {
   "title": "$state Jobs per Partition ($partition)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "slurm_partition_job_state_total{state=~\"$state\", instance=\"$instance\", partition=~\"$partition\"}",
     "legendFormat": "{{partition}} {{state}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Slurm Node States",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "slurm_node_count_per_state{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cluster Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(slurm_partition_free_mem{instance=\"$instance\"} / slurm_partition_real_mem{instance=\"$instance\"}) ",
     "legendFormat": "Ave memFree"
    },
    {
     "expr": "avg(slurm_partition_alloc_mem{instance=\"$instance\"} / slurm_partition_real_mem{instance=\"$instance\"})",
     "legendFormat": "Ave memA"
    },
    {
     "expr": "avg(slurm_partition_cpu_load{instance=\"$instance\"} / slurm_partition_total_cpus{instance=\"$instance\"})",
     "legendFormat": "Ave cpuL"
    }
   ]
  },
  { "title": "Account ($account) Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Account ($account) CPU alloc $state",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "slurm_account_job_state_cpu_alloc{instance=\"$instance\", account=~\"$account\", state=~\"$state\"}",
     "legendFormat": "{{account}} {{state}}"
    },
    {
     "expr": "sum(slurm_account_job_state_cpu_alloc{instance=\"$instance\"})",
     "legendFormat": "TOTAL ALLOC"
    },
    {
     "expr": "slurm_cpus_total{instance=\"$instance\"}",
     "legendFormat": "TOTAL CPUS"
    }
   ]
  },
  {
   "title": "Account ($account) Mem Alloc",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "slurm_account_job_state_mem_alloc{instance=\"$instance\", account=~\"$account\"}",
     "legendFormat": "{{account}}"
    },
    {
     "expr": "sum(slurm_account_job_state_mem_alloc{instance=\"$instance\"})",
     "legendFormat": "TOTAL ALLOC"
    },
    {
     "expr": "sum(slurm_mem_real{instance=\"$instance\"})",
     "legendFormat": "TOTAL MEM"
    }
   ]
  },
  {
   "title": "Account ($account) Jobs $state",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "slurm_account_job_state_total{instance=\"$instance\",state=~\"$state\", account=~\"$account\"}",
     "legendFormat": "{{account}} {{state}}"
    }
   ]
  },
  { "title": "User Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "User Totals - RUNNING CPU",
   "type": "timeseries",
   "description": "Total CPUS that are in the state RUNNING",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "slurm_user_cpu_alloc{state=\"RUNNING\", username=~\"($user|${__user.login})\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Job Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tracked Usage %",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "slurm_proc_cpu_usage / on(jobid) group_right() slurm_job_cpu_alloc",
       "legendFormat": "{{jobid}} cpu usage %"
      },
      {
       "expr": "slurm_proc_mem_usage / on(jobid) group_right() (slurm_job_mem_alloc * 1000)",
       "legendFormat": "{{jobid}} mem usage %"
      }
     ]
    },
    {
     "title": "Read/Write bytes",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "rate(slurm_proc_read_bytes[$__rate_interval])",
       "legendFormat": "{{jobid}} read_bytes"
      },
      {
       "expr": "rate(slurm_proc_write_bytes[$__rate_interval])",
       "legendFormat": "{{jobid}} write_bytes"
      }
     ]
    },
    {
     "title": "Usage vs Alloc (Mem) for jobid: $jobid",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "slurm_proc_mem_usage{jobid=\"$jobid\"}",
       "legendFormat": "{{jobid}} usage"
      },
      {
       "expr": "slurm_job_mem_alloc{jobid=\"$jobid\"}",
       "legendFormat": "{{jobid}} alloc"
      }
     ]
    },
    {
     "title": "Usage vs Alloc (Cpu) for jobid: $jobid",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "slurm_proc_cpu_usage{jobid=\"$jobid\"}",
       "legendFormat": "{{jobid}} usage"
      },
      {
       "expr": "slurm_job_cpu_alloc{jobid=\"$jobid\"}*100",
       "legendFormat": "{{jobid}} alloc"
      }
     ]
    }
   ]
  },
  {
   "title": "Slurmctld Diagnostics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Count Per Message Type per $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "rate(slurm_rpc_msg_type_count[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "RPC Count Per User per $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "rate(slurm_rpc_user_count[$__rate_interval])",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Avg Time per RPC per MSG",
     "type": "timeseries",
     "description": "Only show latencies above 100 microseconds (1 ms)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(slurm_rpc_msg_type_avg_time{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Avg Time per RPC per User",
     "type": "timeseries",
     "description": "Only show latencies above 100 microseconds (1 ms)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "(rate(slurm_rpc_user_total_time{instance=\"$instance\"}[$__rate_interval]) / on(user) rate(slurm_rpc_user_count{instance=\"$instance\"}[$__rate_interval])) > 100",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Msg Type Summary",
     "type": "piechart",
     "description": "Percentage load per Msg Type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(slurm_rpc_msg_type_count{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Top 25 Users",
     "type": "piechart",
     "description": "Top 25 Users by RPC Count",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(25, rate(slurm_rpc_user_count{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{user}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter  Mem Usage",
     "type": "timeseries",
     "description": "Number of bytes allocated and in use",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"slurm-prod-scraper\", instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrape Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "rate(slurm_job_scrape_error{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "job scrape error"
      },
      {
       "expr": "rate(slurm_node_scrape_error{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "node scrape error"
      },
      {
       "expr": "rate(slurm_diag_scrape_error{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "diag scrape error"
      }
     ]
    },
    {
     "title": "Exporter cli scrape duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "slurm_node_scrape_duration{instance=\"$instance\"}",
       "legendFormat": "sinfo cli duration"
      },
      {
       "expr": "slurm_job_scrape_duration{instance=\"$instance\"}",
       "legendFormat": "squeue cli duration"
      },
      {
       "expr": "slurm_diag_scrape_duration{instance=\"$instance\"}",
       "legendFormat": "sdiag scrape duration"
      }
     ]
    }
   ]
  }
 ]
}