---
# Many provisioning systems, especially for Ubuntu, will include cloud-init
# as part of the initial setup process for networking and other configuration.
#
# However, DeepOps attempts to manage many of the same files, which can lead to
# conflicts and some components breaking under certain circumstances. /etc/hosts
# is a good example of a file that both systems try to manage.
#
# This playbook disables cloud-init to prevent DeepOps and cloud-init from
# stepping on each other.

- name: Disable cloud-init
  hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Check if /etc/cloud is present
      ansible.builtin.stat:
        path: "/etc/cloud"
      when: deepops_disable_cloud_init | default(true)
      register: etc_cloud

    - name: Disable generator for setting cloud-init target
      ansible.builtin.file:
        path: "/etc/cloud/cloud-init.disabled"
        owner: "root"
        group: "root"
        mode: "0644"
        state: "touch"
      when: (deepops_disable_cloud_init | default(true)) and etc_cloud.stat.exists

    - name: Disable all systemd services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - "cloud-init"
        - "cloud-config"
        - "cloud-final"
      when: deepops_disable_cloud_init | default(true)
      failed_when: false # In case services do not exist
