---
- name: Configure hostname and hosts file
  hosts: all
  become: true
  tasks:
    - name: Set /etc/hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      when: deepops_set_hostname | default(true)

    - name: Set /etc/hosts
      ansible.builtin.include_role:
        name: DeepOps.hosts
      vars:
        hosts_add_ansible_managed_hosts: true
