---
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - ../vars
      skip: true
  tags:
    - always

- name: Configure alternative library path
  ansible.builtin.template:
    src: ld-openmpi.conf.j2
    dest: /etc/ld.so.conf.d/openmpi.conf
    mode: "0644"
  register: updated_openmpi_ld

- name: Update ld cache
  ansible.builtin.command: ldconfig
  when: updated_openmpi_ld.changed # noqa no-handler

- name: Default to building openmpi
  ansible.builtin.set_fact:
    openmpi_build: true

- name: Check installed openmpi version
  ansible.builtin.shell: "{{ openmpi_install_prefix }}/bin/ompi_info | grep 'Open MPI:' | awk '{print $3}'"
  register: openmpi_info_version
  ignore_errors: true
  changed_when: openmpi_info_version.rc != 0

- name: Don't build openmpi if it's already installed, unless forced
  ansible.builtin.set_fact:
    openmpi_build: false
  when: openmpi_info_version.stdout == openmpi_version and not openmpi_force_rebuild

- name: Install openmpi build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ openmpi_deps }}"
  when: ansible_distribution == 'Ubuntu'

- name: Install openmpi build dependencies
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ openmpi_deps }}"
  when: ansible_os_family == 'RedHat'

- name: Remove openmpi packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
  when: ansible_distribution == 'Ubuntu'
  failed_when: false

- name: Remove openmpi packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - openmpi
    - openmpi-devel
  when: ansible_os_family == 'RedHat'
  failed_when: false

- name: Make openmpi build directory
  ansible.builtin.file:
    path: "{{ openmpi_build_dir }}"
    state: directory
    mode: "0755"
  when: openmpi_build

- name: Download openmpi source
  ansible.builtin.unarchive:
    src: "{{ openmpi_src_url }}"
    remote_src: true
    dest: "{{ openmpi_build_dir }}"
    extra_opts:
      - --strip-components=1
  when: openmpi_build

- name: Uninstall old openmpi version
  community.general.make:
    chdir: "{{ openmpi_build_dir }}"
    target: uninstall
    jobs: 4
  failed_when: false
  when: openmpi_build
  tags:
    - uninstall

- name: Clean openmpi src dir
  community.general.make:
    chdir: "{{ openmpi_build_dir }}"
    target: distclean
    jobs: 4
  failed_when: false
  when: openmpi_build

- name: Configure openmpi
  ansible.builtin.command:
    cmd: ./configure {{ openmpi_configure_args | join(' ') }}
    chdir: "{{ openmpi_build_dir }}"
    creates: "{{ openmpi_build_dir }}/config.status"
  when: openmpi_build

- name: Build openmpi
  community.general.make:
    chdir: "{{ openmpi_build_dir }}"
    jobs: "{{ ansible_processor_vcpus | default(1) }}"
    target: all
  when: openmpi_build

- name: Install openmpi
  community.general.make:
    chdir: "{{ openmpi_build_dir }}"
    target: install
    jobs: 4
  when: openmpi_build

- name: Run ldconfig to ensure libs are found
  ansible.builtin.command:
    cmd: ldconfig
  changed_when: false
  when: openmpi_build
