---
- hosts: all
  become: true
  tasks:
    - name: ensure man directories exist in minimal ubuntu image
      ansible.builtin.file:
        path: "/usr/share/man/man1"
        owner: "root"
        group: "root"
        state: "directory"
        mode: "0755"
      when: ansible_distribution == "Ubuntu"

    - name: Ensure dependencies are present for apt key management
      ansible.builtin.apt:
        update_cache: true
        name: "gpg-agent"
        state: present
      when: ansible_distribution == "Ubuntu"
