---
- name: Apt install pciutils
  ansible.builtin.apt:
    name: pciutils
    update_cache: "yes"
  when: ansible_os_family == 'Debian'
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Yum install pciutils
  ansible.builtin.dnf:
    name: pciutils
    update_cache: "yes"
  when: ansible_os_family == 'RedHat'
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Create fact directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: Custom facts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/ansible/facts.d/
    mode: "0755"
  with_fileglob:
    - "*"

- name: Regather local facts
  ansible.builtin.setup:
    filter: ansible_local
