slurm_exporter_enabled: yes

slurm_exporter_container: "deepops-slurm-exporter:latest"
slurm_exporter_version: "1.6.4"
slurm_exporter_config_dir: "{{ deepops_dir }}/slurm-exporter"
slurm_exporter_port: 8080
slurm_exporter_log_level: "info"
slurm_exporter_svc_name: "docker.slurm-exporter.service"
slurm_exporter_state: started

slurm_install_prefix: /usr/local

prometheus_config_dir: /etc/prometheus
prometheus_cfg_endpoint_dir: "{{ prometheus_config_dir }}/endpoints"
slurm_exporter_conf_template: "slurm-exporter.yml.j2"

grafana_svc_name: "docker.grafana.service"
grafana_data_dir: /var/lib/grafana
grafana_cfg_dashboard_path: "{{ grafana_data_dir }}/dashboards"
grafana_user_id: 472

slurm_exporter_host_group: "{{ slurm_monitoring_group | default('slurm-master') }}"
