---
- name: Install docker
  import_playbook: docker.yml

- name: Install nginx docker registry cache client
  hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Configure nginx container caching proxy client
      include_role:
        name: "nginx-docker-registry-cache"
        tasks_from: client
