---
- name: Configure Pyxis on controller nodes
  hosts: slurm-master
  tasks:
    - name: Set controller fact
      ansible.builtin.set_fact:
        is_controller: true
      tags: always

- name: Configure pyxis on non-controller nodes
  hosts: slurm-node
  tasks:
    - name: Set compute fact
      ansible.builtin.set_fact:
        is_compute: true
      tags: always

- name: Configure enroot on all nodes
  hosts: slurm-cluster
  become: true
  tasks:
    - name: Set enroot DGX config fact
      ansible.builtin.set_fact:
        enroot_environ_config_files: "{{ enroot_environ_config_files_dgx }}"
      when: ansible_product_name is search("DGX")

- name: Set up enroot on compute nodes
  hosts: slurm-node
  become: true
  roles:
    - name: nvidia.enroot

- name: Set up pyxis on all nodes
  hosts: slurm-cluster
  become: true
  roles:
    - name: pyxis
