---
# Slurm Cluster Playbook

- name: Install Slurm
  import_playbook: slurm-cluster/slurm.yml

- name: Install OpenMPI
  import_playbook: slurm-cluster/openmpi.yml
  when: slurm_cluster_install_openmpi | default(true)

- name: Install Lmod
  import_playbook: slurm-cluster/lmod.yml
  when: slurm_install_lmod

- name: Install the NVIDIA HPC SDK
  import_playbook: nvidia-software/nvidia-hpc-sdk.yml
  vars:
    hostlist: "{{ sm_install_host | default('slurm-login[0]')}}"
  when: slurm_install_hpcsdk

- name: Install monitoring services | Install prometheus
  import_playbook: slurm-cluster/prometheus.yml
  vars:
    hostlist: "{{ slurm_monitoring_group | default('slurm-metric') }}"
  when: slurm_enable_monitoring

- name: Install monitoring services | Install grafana
  import_playbook: slurm-cluster/grafana.yml
  vars:
    hostlist: "{{ slurm_monitoring_group | default('slurm-metric') }}"
  when: slurm_enable_monitoring

- name: Install monitoring services | Install alert manager
  import_playbook: slurm-cluster/alertmanager.yml
  vars:
    hostlist: "{{ slurm_monitoring_group | default('slurm-metric') }}"
  when: slurm_enable_monitoring

# Install monitoring exporters
- name: Install monitoring exporters | Install prometheus slurm exporter
  import_playbook: slurm-cluster/prometheus-slurm-exporter.yml
  vars:
    hostlist: "{{ slurm_monitoring_group | default('slurm-metric') }}"
  when: slurm_enable_monitoring

- name: Install monitoring exporters | Install prometheus node exporter
  import_playbook: slurm-cluster/prometheus-node-exporter.yml
  when: slurm_enable_monitoring

- name: Install monitoring exporters | Install nvidia dcgm exporter
  import_playbook: slurm-cluster/nvidia-dcgm-exporter.yml
  when: slurm_enable_monitoring

- name: Set up rsyslog forwarding from compute nodes to head node | Install rsyslog server
  import_playbook: generic/rsyslog-server.yml
  vars:
    hostlist: "{{ rsyslog_server_hostname | default('slurm-master[0]') }}"
  when: slurm_enable_rsyslog_server | default(true)

- name: Set up rsyslog forwarding from compute nodes to head node | Install rsyslog client
  import_playbook: generic/rsyslog-client.yml
  vars:
    hostlist: "{{ rsyslog_client_group | default('slurm-node') }}"
  when: slurm_enable_rsyslog_client | default(true)

- name: Install Singularity
  import_playbook: container/singularity.yml
  when: slurm_cluster_install_singularity | default(true)

- name: Install Open OnDemand
  import_playbook: slurm-cluster/open-ondemand.yml
  when: install_open_ondemand

- name: Set Permissions to adjust GPU Clocks speeds
  import_playbook: utilities/gpu-clocks.yml
  when: allow_user_set_gpu_clocks

- name: Install Enroot and Pyxis
  import_playbook: container/pyxis.yml
  when:
    - slurm_install_enroot
    - slurm_install_pyxis
  tags:
    - pyxis

- name: Ensure that nv_peer_mem is loaded
  import_playbook: nvidia-software/nvidia-peer-memory.yml
  tags:
    - nvidia-peer-memory
