#
# install software modules using EasyBuild.
#
---
- name: Install Lmod on all hosts
  hosts: all
  roles:
    - role: lmod

- name: Build easybuild modules on master node
  hosts: slurm-master[0]
  roles:
    - role: easy-build

- name: Install software modules on master node
  hosts: slurm-master[0]
  roles:
    - role: easy-build-packages
