---
- name: Install docker
  import_playbook: ../container/docker.yml

- name: Install Grafana
  hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Configure Grafana container
      ansible.builtin.include_role:
        name: grafana
