---
- name: Install NHC
  hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Gather custom facts
      ansible.builtin.include_role:
        name: facts
    - name: Install Node Health Check
      ansible.builtin.include_role:
        name: nhc
