---
- name: Install docker
  import_playbook: ../container/docker.yml

- name: Install NVIDIA driver
  import_playbook: ../nvidia-software/nvidia-driver.yml

- name: Install NVIDIA container runtime
  import_playbook: ../container/nvidia-docker.yml

- name: Install NVIDIA DCGM Exporter
  hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Install custom facts module
      ansible.builtin.import_role:
        name: facts

    - name: Set GPU facts
      ansible.builtin.set_fact:
        has_gpus: true
      when: ansible_local['gpus']['count'] > 0 | default(false)

    - name: Configure DCGM exporter
      ansible.builtin.import_role:
        name: nvidia-dcgm-exporter
      when: ansible_distribution == "Ubuntu" or ansible_os_family == "RedHat"
