---
- name: Install Open OnDemand server on master node
  hosts: slurm-controller[0]
  become: true
  roles:
    - role: ood-wrapper
      vars:
        ood_is_server: true

- name: Install Open OnDemand client on compute nodes
  hosts: slurm-node
  become: true
  roles:
    - role: ood-wrapper
      vars:
        ood_is_client: true
