---
- name: Install docker
  import_playbook: ../container/docker.yml

- name: "Install monitoring exporters | Install prometheus slurm exporter"
  hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Configure prometheus slurm exporter
      ansible.builtin.include_role:
        name: prometheus-slurm-exporter
