---
- name: Install docker
  import_playbook: ../container/docker.yml

- name: Configure Prometheus Node Exporter
  hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Configure Prometheus Node Exporter
      ansible.builtin.include_role:
        name: prometheus-node-exporter
