---
- name: Gather facts
  hosts: all
  become: true
  roles:
    - role: facts

- name: Set root SSH key to allow SSH/ansible when no slurm job running for ansible user
  hosts: slurm-node
  become: true
  tasks:
    - name: Add SSH public key to root user authorized keys
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', ansible_ssh_private_key_file | default(lookup('env', 'HOME') + '/.ssh/id_rsa') + '.pub') }}"

- name: Build slurm on all nodes
  hosts: slurm-cluster
  become: true
  tasks:
    - name: Build slurm on all nodes
      ansible.builtin.include_role:
        name: slurm
        tasks_from: build

- name: Set is_misc fact on all nodes (will be cleared on compute and controller nodes)
  hosts: slurm-cluster
  tasks:
    - name: Set misc fact
      ansible.builtin.set_fact:
        is_misc: true
      tags: always

- name: Set is_controller fact on controller nodes
  hosts: slurm-controller
  tasks:
    - name: Set controller fact
      ansible.builtin.set_fact:
        is_controller: true
        is_misc: false
      tags: always

- name: Set is_compute fact on compute nodes
  hosts: slurm-node
  tasks:
    - name: Set compute fact
      ansible.builtin.set_fact:
        is_compute: true
        is_misc: false
      tags: always

- name: Set up slurm on all nodes
  hosts: slurm-cluster
  become: true
  roles:
    - role: slurm
      vars:
        user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        slurm_workflow_build: false

- name: Set up slurm-login-on-compute if enabled
  hosts: slurm-controller
  become: true
  tasks:
    - name: Setup slurm login on compute if enabled.
      ansible.builtin.include_role:
        name: slurm
        tasks_from: login-compute-setup
      vars:
        user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        is_controller: true
      when: slurm_login_on_compute | default(false)
