---
- name: create pyxis source dir
  ansible.builtin.file:
    path: /usr/local/src/pyxis
    state: directory
    mode: "0755"
  tags: pyxis

- name: copy pyxis source
  ansible.builtin.unarchive:
    src: "{{ slurm_pyxis_tarball_url }}"
    remote_src: true
    dest: /usr/local/src/pyxis
    extra_opts:
      - --strip-components=1
  tags: pyxis

- name: clean pyxis source directory
  ansible.builtin.command:
    chdir: /usr/local/src/pyxis
    argv:
      - make
      - clean
  register: pyxis_make_clean
  failed_when: false
  changed_when: pyxis_make_clean.rc == 0
  tags: pyxis

- name: build pyxis
  ansible.builtin.command:
    chdir: /usr/local/src/pyxis
    argv:
      - make
      - -j
  environment:
    CPPFLAGS: "-I {{ slurm_install_prefix }}/include/slurm"
  register: result
  changed_when: 'result.stdout != "make: Nothing to be done for ''all''."'
  notify:
    - Restart slurmctld
    - Restart slurmd
  tags: pyxis

# Needed for 17.11, but not for 19.05. Doesn't hurt either way.
- name: copy top-level plugstack file
  ansible.builtin.template:
    src: etc/slurm/plugstack.conf
    dest: "{{ slurm_config_dir }}/"
    mode: "0644"
  notify:
    - Restart slurmctld
    - Restart slurmd
  tags: pyxis

- name: copy pyxis plugstack file
  ansible.builtin.template:
    src: etc/slurm/plugstack.conf.d/pyxis.conf
    dest: "{{ slurm_config_dir }}/plugstack.conf.d/"
    mode: "0644"
  notify:
    - Restart slurmctld
    - Restart slurmd
  tags: pyxis

- name: set pyxis shared-object permissions
  ansible.builtin.file:
    path: "/usr/local/src/pyxis/spank_pyxis.so"
    mode: "0755"
