---
# Install NVIDIA CUDA (and driver if present)

- name: Install NVIDIA CUDA (and driver if present)
  hosts: "{{ hostlist | default('all') }}"
  become: true
  environment: "{{ proxy_env if proxy_env is defined else{} }}"
  tasks:
    - name: Check for DGX packages
      ansible.builtin.stat:
        path: /etc/dgx-release
      register: is_dgx

    - name: Install custom facts
      ansible.builtin.include_role:
        name: facts

    - name: Install nvidia driver
      ansible.builtin.include_role:
        name: nvidia.nvidia_driver
      when:
        - ansible_local['gpus']['count'] | bool | default(false)
        - is_dgx.stat.exists is False
        - cuda_playbook_install_driver | default(true)
      tags:
        - nvidia_driver

    - name: Install nvidia cuda toolkit
      ansible.builtin.include_role:
        name: nvidia_cuda

    - name: Test nvidia-smi
      ansible.builtin.command: nvidia-smi
      changed_when: false
      when:
        - ansible_local['gpus']['count'] | bool | default(false)
        - cuda_playbook_install_driver | default(true)
      tags:
        - nvidia_driver
