---
- name: install dependencies (ubuntu)
  ansible.builtin.apt:
    name:
      - "uidmap"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install dependencies (Red Hat)
  ansible.builtin.yum:
    name:
      - "shadow-utils"
      - "fuse-overlayfs"
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure directory structure exists
  ansible.builtin.file:
    path: "{{ rootlessdocker_install_dir }}/{{ item.path }}"
    owner: "root"
    group: "root"
    state: directory
    mode: "0755"
  with_filetree: "{{ role_path }}/templates/rootless-docker"
  when: item.state == 'directory'

- name: Copy over templates.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ rootlessdocker_install_dir }}/{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
    force: false
  with_filetree: "{{ role_path }}/templates/rootless-docker"
  when: item.state == 'file'

- name: add rootless docker profile script to source modules
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
    force: false
  with_items:
    - "z96_rootlessdocker_modules.sh"

- name: check if rootless docker already installed successfully
  ansible.builtin.stat:
    path: "{{ rootlessdocker_install_dir }}/config/install_success"
  register: rootless_docker_installed

- name: Template setup rootless docker script
  ansible.builtin.template:
    src: "{{ role_path }}/templates/rootless_docker_setup.sh.j2"
    dest: /tmp/rootless_docker_setup.sh
    mode: "0755"
  when: not rootless_docker_installed.stat.exists

- name: Execute setup rootless docker script
  become: true
  ansible.builtin.command: /tmp/rootless_docker_setup.sh
  args:
    executable: /bin/bash
    creates: "{{ rootlessdocker_install_dir }}/config/install_success"

- name: Clean up rootless docker set script
  ansible.builtin.file:
    path: /tmp/rootless_docker_setup.sh
    state: absent

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Load br_netfilter module at boot
  lineinfile:
    path: /etc/modules
    create: true
    line: "br_netfilter"
    owner: "root"
    group: "root"
    mode: "0644"
